FROM golang:1.27

WORKDIR /app

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-eng \
    poppler-utils \
    python3 \
    python3-pil \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/air-verse/air@latest

ENV GOCACHE=/tmp/.cache

COPY go.mod go.sum ./

RUN go mod download

COPY ./ ./

EXPOSE 8081

CMD ["air"]