services:
  frontend:
    container_name: reflex-tech-bookkeping-app-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    environment:
      - DOCUMENTS_PATH=${DOCUMENTS_PATH:-/app/documents}
      - CGO_ENABLED=1
    volumes:
      - ./backend:/app
      - ./document-data:/app/documents
    user: "1000:1000"
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:18.4-alpine3.24
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-reflex-tech-bookkeeping-app-postgres-db}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped

  scanner-smb:
    container_name: scanner-smb
    image: dperson/samba
    environment:
      - USERID=1000 # Matches the backend user so file permissions align
      - GROUPID=1000
    ports:
      - "139:139"
      - "445:445"
    volumes:
      # We map the exact same inbox folder that the backend is watching
      - ./document-data/inbox:/mnt/inbox
    # Creates user 'scanner' with password 'password123'
    # Creates a share named 'inbox' pointing to /mnt/inbox
    command: '-u "scanner;password123" -s "inbox;/mnt/inbox;yes;no;no;scanner"'
    restart: unless-stopped

networks:
  default:
    name: reflex-tech-bookkeeping-app-network

volumes:
  postgres-data:
    name: postgres-data